Crossrail.ObservationForm.Mvc/Models/ModelStateWrapper.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Crossrail.ObservationForm.Business.Validation;

namespace Crossrail.ObservationForm.Mvc.Models
{
    /// <summary>
    /// An implementation of <see cref="IValidationDictionary"/> for
    /// passing model state into the service layer to add more complex
    /// validation messages.
    /// </summary>

    public class ModelStateWrapper : IValidationDictionary
    {
        private readonly ModelStateDictionary _modelState;

        public ModelStateWrapper(ModelStateDictionary modelState)
        {
            _modelState = modelState;
        }

        #region IValidationDictionary Members

        public void AddError(string key, string errorMessage)
        {
            _modelState.AddModelError(key, errorMessage);
        }

        public void Remove(string key)
        {
            _modelState.Remove(key);
        }

        public bool IsValid
        {
            get { return _modelState.IsValid; }
        }

        #endregion
    }
}

Crossrail.ObservationForm.Mvc/Controllers/BaseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Crossrail.ObservationForm.Business;

namespace Crossrail.ObservationForm.Mvc.Controllers
{
    /// <summary>
    /// Base controller with unit of work for easy access to 
    /// service layer within controllers.
    /// </summary>

    [OutputCache(NoStore = true, Duration = 0, VaryByParam = "*")]
    public class BaseController : Controller
    {
        private UnitOfWork _unitOfWork;

        /// <summary>
        /// Use for the entire lifecycle of the controller. Disposed in <see cref="Dispose"/>
        /// </summary>

        protected UnitOfWork UnitOfWork 
        { 
            get { return _unitOfWork ?? (_unitOfWork = new UnitOfWork()); } 
        }

        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);

            if (_unitOfWork != null)
            {
                _unitOfWork.Dispose();
            }
        }
    }
}

Crossrail.ObservationForm.Mvc/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Crossrail.ObservationForm.Mvc.Controllers
{
    public class HomeController : BaseController
    {
        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }
    }
}

Crossrail.ObservationForm.Mvc/Controllers/ObservationsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Crossrail.ObservationForm.Domain;
using Crossrail.ObservationForm.Mvc.Mailers;
using Crossrail.ObservationForm.Mvc.Models;
using SimpleHoneypot.ActionFilters;

namespace Crossrail.ObservationForm.Mvc.Controllers
{
    /// <summary>
    /// NOTE: At present only the create and index methods are used. The details and index
    /// views are probably incomplete at this stage and do not work.
    /// </summary>

    public class ObservationsController : BaseController
    {
        // GET: /Observations/

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Thanks()
        {
            ViewBag.Thanks = "Thank you for your submission";
            return View();
        }

        private ActionResult Administration()
        {
            IQueryable<Observation> observations = UnitOfWork.ObservationService
                .GetAll()
                .OrderByDescending(o => o.ObservationDate);
            
            return View(observations);
        }

        //
        // GET: /Observations/Create

        public ActionResult Create(HttpPostedFileBase file)
        {
            PopulateViewBag();
            return View();
        }

        private void PopulateViewBag()
        {
            ViewBag.Contracts = UnitOfWork.ContractService.GetAll().ToList().Select(x => new SelectListItem
            {
                Value = x.ContractId.ToString(),
                Text = x.Name
            });

            ViewBag.Types = UnitOfWork.ObservationService.GetAllTypes().ToList().Select(x => new SelectListItem
            {
                Value = x.ObservationTypeId.ToString(),
                Text = x.Name
            });

            ViewBag.Categories = UnitOfWork.ObservationService.GetAllCategories().ToList().Select(x => new SelectListItem
            {
                Value = x.ObservationCategoryId.ToString(),
                Text = x.Name
            });

            ViewBag.Time = null;
        }

        //
        // POST: /Observations/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        //Redirect to the Thanks page even when honey-pot fails 
        [Honeypot(redirectUrl: "/Observations/Thanks")]

        public ActionResult Create(Observation model, HttpPostedFileBase file)
        {
            //Extra complex validation is performed within the service to method,
            //then the model state validity is used.

            Observation observation = UnitOfWork.ObservationService.Add(
                new ModelStateWrapper(ModelState), model, file);
            
            if (observation != null)
            {
                //Email if specified

                if (!string.IsNullOrWhiteSpace(observation.Email))
                {
                    var observationsMailer = new ObservationsMailer();
                    observationsMailer.Details(observation).Send();
                }

                return RedirectToAction("Thanks");
            }
            
            PopulateViewBag();
            return View(model);
        }

        //
        // GET: /Observations/Edit/5

        private ActionResult Edit(int id = 0)
        {
            var observation = UnitOfWork.ObservationService.GetById(id);

            if (observation == null)
            {
                return HttpNotFound();
            }

            PopulateViewBag();
            return View(observation);
        }

        //
        // POST: /Observations/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        private ActionResult Edit(int id, Observation model, HttpPostedFileBase file)
        {
            //Assign the ID manually from the URL since we cannot change the default
            //"id" parameter name in the GET without either creating a custom binder + attribute
            //or change the routing set-up.

            model.ObservationId = id;

            Observation observation = UnitOfWork.ObservationService.Edit(
                new ModelStateWrapper(ModelState), model, file);

            if (observation != null)
            {
                //No need to send an email on the edit? Can we remove
                //the field from the view?

                return RedirectToAction("Administration");
            }

            PopulateViewBag();
            return View(model);
        }

        //
        // GET: /Observations/Delete/5

        private ActionResult Delete(int id = 0)
        {
            Observation observation = UnitOfWork.ObservationService.GetById(id);

            if (observation == null)
            {
                return HttpNotFound();
            }

            return View(observation);
        }

        // GET: /Observations/Details/5

        private ActionResult Details(int id = 0)
        {
            Observation observation = UnitOfWork.ObservationService.GetById(id);

            if (observation == null)
            {
                return HttpNotFound();
            }

            return View(observation);
        }

        //
        // POST: /Observations/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        private ActionResult DeleteConfirmed(int id)
        {
            UnitOfWork.ObservationService.Remove(id);
            UnitOfWork.SaveChanges();

            return View();
        }
    }
}

Crossrail.ObservationForm.Mvc/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Crossrail - Observation Form";
}

Crossrail.ObservationForm.Mvc/Views/Observations/Administration.cshtml
@using Crossrail.ObservationForm.Business
@using Crossrail.ObservationForm.Mvc.Extensions

@model IEnumerable<Crossrail.ObservationForm.Domain.Observation>

@{
    ViewBag.Title = "AdminDetails";
}

<table class="table content-block">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ContractId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ObservationTypeId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ObservationCategoryName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Location)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ObservationDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ReportedBy)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </th>
        <th>
            Image
        </th>
        <th>
            Edit
        </th>
        @*<th>
            Delete
        </th>*@
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Contract.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ObservationType.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ObservationCategoryName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Location)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ObservationDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ReportedBy)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PhoneNumber)
            </td>
            <td>
                @* May need a better way of adding this URL into here long term *@
                @Url.ContentWithDefault(ObservationService.GetVirtualPath(item.FilePath), "View", new { target="_blank" })
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.ObservationId })
            </td>

            @* TODO: Can we improve this?
            <td>
                @using (Html.BeginForm("Delete", "Observations", new { id = item.ObservationId }))
                {
                    @Html.AntiForgeryToken()
                    <input type="submit" value="Delete" />
                }

                @Html.ActionLink("Details", "Details", new { id = item.ObservationId }) |
            </td>
            *@
        </tr>
    }

</table>

    <div class="content-block">
        @Html.ActionLink("Go Back", "Index", null, new { @class = "button" })
    </div>

Crossrail.ObservationForm.Mvc/Views/Observations/Create.cshtml
@model Crossrail.ObservationForm.Domain.Observation
@{
    ViewBag.Title = "Index";
}

@Html.Partial("Form", Model)

Crossrail.ObservationForm.Mvc/Views/Observations/Delete.cshtml
@model Crossrail.ObservationForm.Domain.Observation

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>Observation</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.ContractId)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ContractId)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.ObservationTypeId)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ObservationTypeId)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Location)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Location)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.ObservationDate)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ObservationDate)
    </div>
    
    @*<div class="display-label">
         @Html.DisplayNameFor(model => model.Time)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Time)
    </div>*@

    <div class="display-label">
         @Html.DisplayNameFor(model => model.ObservationCategoryId)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ObservationCategoryId)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.BriefDescription)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.BriefDescription)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.OtherCategory)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.OtherCategory)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.ReportedBy)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ReportedBy)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.PhoneNumber)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.PhoneNumber)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.ActionsTaken)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ActionsTaken)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.ContractorInvolved)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ContractorInvolved)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.FilePath)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.FilePath)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Email)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Email)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.CompanyObservationReference)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.CompanyObservationReference)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

Crossrail.ObservationForm.Mvc/Views/Observations/Details.cshtml
@model Crossrail.ObservationForm.Domain.Observation

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>Observation</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.ContractId)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ContractId)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.ObservationTypeId)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ObservationTypeId)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Location)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Location)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.ObservationDate)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ObservationDate)
    </div>
    
   @* <div class="display-label">
         @Html.DisplayNameFor(model => model.Time)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Time)
    </div>*@

    <div class="display-label">
         @Html.DisplayNameFor(model => model.ObservationCategoryId)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ObservationCategoryId)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.BriefDescription)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.BriefDescription)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.OtherCategory)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.OtherCategory)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.ReportedBy)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ReportedBy)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.PhoneNumber)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.PhoneNumber)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.ActionsTaken)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ActionsTaken)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.ContractorInvolved)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ContractorInvolved)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.FilePath)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.FilePath)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Email)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Email)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.CompanyObservationReference)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.CompanyObservationReference)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.ObservationId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Crossrail.ObservationForm.Mvc/Views/Observations/Edit.cshtml
@model Crossrail.ObservationForm.Domain.Observation

@{
    ViewBag.Title = "Edit";
}

@Html.Partial("Form", Model)

Crossrail.ObservationForm.Mvc/Views/Observations/Form.cshtml
@using Crossrail.ObservationForm.Mvc.Extensions
@using SimpleHoneypot.HtmlHelpers
@model Crossrail.ObservationForm.Domain.Observation

@using (Html.BeginForm(null, null, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <!-- CSRF Token -->
    @Html.AntiForgeryToken()

    //HoneyPot - Prevents spam by adding a hidden input field for bots.
    <div class="field field-hidden">
        @Html.HoneypotInput()
    </div>
    
    <!-- Contract Number -->
    <div class="field">

        <div class="label-block">
            @Html.FieldLabelFor(model => model.ContractId)
        </div>

        <div class="field-value field-value-block">

            @Html.RadioButtonGroupFor(
                model => model.ContractId, 
                new SelectList(ViewBag.Contracts, "Value", "Text"), 
                new { @class = "field-radio-item" })
            
            @Html.ValidationMessageFor(model => model.ContractId)
        </div>
    </div>
        
    <!-- Type of Observation -->
    <div class="field">
        
        @Html.FieldLabelFor(model => model.ObservationTypeId)

        <div class="field-value">
                
            @Html.RadioButtonGroupFor(
                model => model.ObservationTypeId, 
                new SelectList(ViewBag.Types, "Value", "Text"), 
                new { @class = "field-radio-item" })
            
            @Html.ValidationMessageFor(model => model.ObservationTypeId)
        </div>
    </div>
    
    <!-- Location of observation -->
    <div class="field">

        @Html.FieldLabelFor(model => model.Location)

        <div class="field-value">
            @Html.EditorFor(model => model.Location)
            @Html.ValidationMessageFor(model => model.Location)
        </div>
    </div>

    <!-- Date of observation -->
    <div class="field">
        @Html.FieldLabelFor(model => model.ObservationDate)

        <div class="field-value">
            @Html.EditorFor(model => model.ObservationDate)
            @Html.ValidationMessageFor(model => model.ObservationDate)
        </div>
    </div>
        
    <!-- Time of observation -->
    <div class="field">
        @Html.FieldLabelFor(model => model.ObservationTime)

        <div class="field-value">
            @Html.EditorFor(model => model.ObservationTime, "Time")
            @Html.ValidationMessageFor(model => model.ObservationTime)
        </div>
    </div>
        
    <!-- Description of observation -->
    <div class="field">

        @Html.FieldLabelFor(model => model.BriefDescription)

        <div class="field-value">
            @Html.TextAreaFor(model => model.BriefDescription, new { @class = "textarea", @placeholder = "Enter text here" })
            @Html.ValidationMessageFor(model => model.BriefDescription)
        </div>
    </div>
        
    <!-- Category of Observation -->
    <div class="field" id="observation-category">
            
        @Html.FieldLabelFor(model => model.ObservationCategoryId, new { @class = "label-block" })

        <div class="field-value field-value-block">
            @Html.RadioButtonGroupFor(model => model.ObservationCategoryId,
                new SelectList(ViewBag.Categories, "Value", "Text"),
                new { @class = "field-radio-item" })
            
            @Html.ValidationMessageFor(model => model.ObservationCategoryId)
        </div>
        
        <!-- Category Area -->        
        <div class="field" id="observation-area">
        
            @Html.FieldLabelFor(model => model.OtherCategory)

            <div class="field-value">
                @Html.TextAreaFor(model => model.OtherCategory, new { @class = "textarea" })
                @Html.ValidationMessageFor(model => model.OtherCategory)
            </div>
        </div>
    </div>

    <!-- Reporter -->
    <div class="field">
        @Html.FieldLabelFor(model => model.ReportedBy)

        <div class="field-value">
            @Html.EditorFor(model => model.ReportedBy)
            @Html.ValidationMessageFor(model => model.ReportedBy)
        </div>
    </div>
        
    <!-- Telephone -->
    <div class="field">
        @Html.FieldLabelFor(model => model.PhoneNumber)

        <div class="field-value">
            @Html.EditorFor(model => model.PhoneNumber)
            @Html.ValidationMessageFor(model => model.PhoneNumber)
        </div>
    </div>
        
    <!-- Actions -->
    <div class="field">
        @Html.FieldLabelFor(model => model.ActionsTaken)

        <div class="field-value">
            @Html.TextAreaFor(model => model.ActionsTaken, new { @class = "textarea", @placeholder = "Enter text here" })
            @Html.ValidationMessageFor(model => model.ActionsTaken)
        </div>
    </div>
        
    <!-- Contractor -->
    <div class="field">
        @Html.FieldLabelFor(model => model.ContractorInvolved)

        <div class="field-value">
            @Html.EditorFor(model => model.ContractorInvolved)
            @Html.ValidationMessageFor(model => model.ContractorInvolved)
        </div>
    </div>
        
    <!-- Photo -->
    <div class="field">
        <label for="file">Add a Photo:</label>
        
        <div class="field-value">
            <input type="file" name="file" />
            @Html.ValidationMessage("file")
        </div>
    </div>
    
    <!-- Email -->
    <div class="field">
        @Html.FieldLabelFor(model => model.EmailYesOrNo)

        <div class="field-value">
            @Html.CheckBoxFor(model => model.EmailYesOrNo, new { value = "True", @class = "checkbox" })
            @Html.ValidationMessageFor(model => model.EmailYesOrNo)
        </div>
    </div>
    
    <!-- Email Address -->
    <div class="field" id="observation-email" style="display: none">
        @Html.FieldLabelFor(model => model.Email)

        <div class="field-value">
            @Html.TextBoxFor(model => model.Email, new { @class = "text-box", placeholder = "ex: myname@example.com" })
            @Html.ValidationMessageFor(model => model.Email)
        </div>
    </div>

    <!-- Company Reference -->
    <div class="field">
        @Html.FieldLabelFor(model => model.CompanyObservationReference)

        <div class="field-value">
            @Html.EditorFor(model => model.CompanyObservationReference)
            @Html.ValidationMessageFor(model => model.CompanyObservationReference)
        </div>
    </div>
    
    <div class="content-block">
        <input type="submit" value="Submit" class="button" />
    
        @Html.ActionLink("Cancel", "Index", null, new { @class = "button" })
    </div>
}

Crossrail.ObservationForm.Mvc/Views/Observations/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<p>
    @ViewBag.Thanks
</p>

<div class="content-block">
    
    @Html.ActionLink("Create New Observation", "Create", null, new { @class = "button" })

</div>

<div class="content-image-block">
    <img src="~/Content/images/costain_logo.bmp" alt="" class="costain-logo"/>
    <img src="~/Content/images/Target_Zero.png" alt="" class="target_zero-logo" />
    <img src="~/Content/images/BSIF.jpg" alt="" class="bsif-logo"/>
</div>

Crossrail.ObservationForm.Mvc/Views/Observations/Thanks.cshtml
@{
    ViewBag.Title = "Thanks";
}

<div class="content-thanks">
    <p>
        @ViewBag.Thanks
    </p>
</div>
<div class="content-block">
    <p>
        @Html.ActionLink("Create New Observation", "Create", null, new { @class = "button" })
    </p>
</div>

<div class="content-image-block">
    <img src="~/Content/images/costain_logo_small.png" alt="" class="costain-logo"/>
    <img src="~/Content/images/Target_Zero.png" alt="" class="target_zero-logo" />
    <img src="~/Content/images/BSIF.jpg" alt="" class="bsif-logo"/>
</div>

Crossrail.ObservationForm.Mvc/Views/Shared/EditorTemplates/DateTime.cshtml
@model DateTime?

@* 
    Helper for outputting a textbox for date time that has a "date" CSS class 
    so that it can easily be registered with jQuery UI 
*@

@Html.TextBox("", (Model ?? DateTime.Now).ToShortDateString(), new { @class = "text-box single-line date" })

Crossrail.ObservationForm.Mvc/Views/Shared/EditorTemplates/Time.cshtml
@model DateTime?

@* 
    Helper for outputting a textbox for time that has a "time-spinner" CSS class 
    so that it can easily be registered with jQuery UI 
*@

@Html.TextBox("", (Model ?? DateTime.Now).ToString("HH:mm"), new { @class = "time-spinner" })

Crossrail.ObservationForm.Mvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, maximum-scale=1.0" />

    <title>@ViewBag.Title</title>
    
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/themes/crossrail/css")

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryui")
    @Scripts.Render("~/bundles/app")
</head>
    <body>
        <div class="header">
            <div class="content">
                <img width="68" height="63" src="~/Content/images/crossrail_logo_small.png" alt="" class="crossrail-logo" />

                <div class="content-title">
                <h1>Observations</h1>
                <p>
                    Crossrail Observation form Version 2.0
                </p>
                </div>
            </div>
        </div>
        <div class="content">
            @RenderBody()
        </div>

        @RenderSection("scripts", required: false)
    </body>
</html>